version: '3.7'
services:
  cassandra1:
    image: cassandra:4.1.3
    ports:
      #      - 7070:7000
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra
      # - ./docker/cassandra/cassandra-init.sh:/cassandra-init.sh
    # command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=Mars
      - CASSANDRA_RACK=West
    networks:
      - cass-net
    # restart: always

  cassandra2:
    image: cassandra:4.1.3
    #    ports:
    #      - 7071:7000
    #      - 9043:9042
    volumes:
      - cassandra2_data:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=Mars
      - CASSANDRA_RACK=West
    networks:
      - cass-net
    # restart: always
networks:
  cass-net:
    driver: bridge
volumes:
  cassandra_data:
  cassandra2_data: