version: "3.7"
services:
  postgres-db:
    image: "postgres:14.3"
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - local-network
    environment:
      - POSTGRES_DB=postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis-cluster:
    image: phuongdm1987/docker-redis-cluster:1.0.0
    container_name: redis-cluster
    # restart: always
    ports:
      - "6379-6384:6379-6384"
    environment:
      - "INITIAL_PORT=6379"
      - "MASTERS=3"
      - "SLAVES_PER_MASTER=0"
      - "SENTINEL=false"
      - "REDIS_CLUSTER_IP=0.0.0.0"
      - "IP=0.0.0.0"
      - "BIND_ADDRESS=0.0.0.0"
      - 'DEFAULT_PASSWORD=password'
    networks:
      - local-network
  sftp:
      image: atmoz/sftp
      container_name: sftp-server
      volumes:
          - ./data/upload:/home/user/upload
      ports:
          - "2222:22"
      command: user:password:1777:::upload
  minio:
    image: minio/minio
    container_name: s3-server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: s3user
      MINIO_ROOT_PASSWORD: s3password
    command: server --console-address ":9001" /data
volumes:
  postgres-data:
  minio_storage: 
  redis-cluster_data-0:
  redis-cluster_data-1:
  redis-cluster_data-2:
networks:
  local-network:
